name: Automatic Rebase
on:
  # Run on every push on every branch
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  # Run when pull requests get labeled
  pull_request:
    types: [labeled]

jobs:
  auto-rebase:
    name: AutoRebase
    runs-on: ubuntu-latest
    steps:
      - uses: Label305/AutoRebase@v0.1.10
        with:
          github_token: ${{ secrets.AUTOREBASE_TOKEN }}
