name: Continuous Integration
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.14.3

      - name: Verify formatting
        run: deno fmt --check --config=./deno.json

      - name: Run linter
        run: deno lint --config=./deno.json

      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
        with:
          velociraptor-version: 1.2.0

      - uses: actions/checkout@master
      - name: Running Test
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ job.status }} - ${{ toJson(steps) }}

      - name: Run tests
        run: vr test
